server:
  port: 443
  error:
    include-message: always
  ssl:
    key-store: sslKey
    key-store-password: bill880315
    key-store-type: PKCS12
    key-alias: mysslcertificate

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

aws:
  region: ap-southeast-1
  s3:
    mock: false
    buckets:
      customer: bill-test-s3

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

spring:
  datasource:
    url: jdbc:postgresql://database-1.cxkc0cookn57.ap-southeast-1.rds.amazonaws.com/customer
    username: postgres
    password: bill880315
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB